Test Questions

In [ ]:
# 1) Count the number of occurences of a particular number

# Example input
num_list = [1,2,2,3,4,4,4,5]

counts = {}

for num in num_list:
    counts[num] = counts.get(num, 0) + 1

for number in counts.keys():
    print(f"{number} : {counts[number]}")

1 : 1
2 : 2
3 : 1
4 : 3
5 : 1


In [ ]:
# 2) Grade Calculator

marks = []

# Enter marks of 5 subjects
for i in range(5):
  mark = float(input(f"Enter marks for subject {i+1}: "))
  marks.append(mark)

total_marks = sum(marks)
avg_marks = total_marks / 5

# Grading
if avg_marks >= 90:
    grade = 'A'
elif avg_marks >= 75:
    grade = 'B'
elif avg_marks >= 60:
    grade = 'C'
else:
    grade = 'Fail'

# Display
print(f"Total Marks: {total_marks}")
print(f"Average Marks: {avg_marks}")
print(f"Grade: {grade}")

Enter marks for subject 1: 23
Enter marks for subject 2: 23
Enter marks for subject 3: 3
Enter marks for subject 4: 3
Enter marks for subject 5: 3
Total Marks: 55.0
Average Marks: 11.0
Grade: Fail


In [ ]:
# 3) Marks Analysis

marks = [78, 85, 92, 67, 88, 74, 95]

total_marks = sum(marks)
avg_marks = total_marks / len(marks)

print(f"Average Marks: {avg_marks}")
print(f"Highest Marks: {max(marks)}")
print(f"Lowest Marks: {min(marks)}")
print("Marks Above Average:")

for i in range(len(marks)):
    if marks[i] > avg_marks:
        print(marks[i])

Average Marks: 82.71428571428571
Highest Marks: 95
Lowest Marks: 67
Marks Above Average:
85
92
88
95


In [ ]:
# 4) Function to check palindrome

def is_palindrome(num):
  if num == num[::-1]:
    return True
  else:
    return False

**numpy**

In [3]:
import numpy as np

# to get numpy version
np.__version__

'2.0.2'

In [ ]:
l = [5, 10, 20]
print(type(l))
print(l)

# Lists are heterogeneous and slow.

In [21]:
arr1 = np.array([10, 5, 20])
print(type(arr1))
print(arr1)

arr2 = np.array([10, 20, 3.5])
print("\n")
print(type(arr2))
print(arr2) # converts int to float because of higher priority of complex
print(arr2.dtype)

arr3 = np.array([2, 3-2j, 25])
print("\n")
print(arr3.dtype)
print(arr3) # int type is converted to complex because of higher priority of complex

arr4 = np.array([10, 15, "Hello"])
print("\n")
print(arr4) # int is converted to String
print(arr4.dtype)

# Arrays are homogeneous and fast.
# You can access or modify array elements but cannot delete or remove the elements.

<class 'numpy.ndarray'>
[10  5 20]


<class 'numpy.ndarray'>
[10.  20.   3.5]
float64


complex128
[ 2.+0.j  3.-2.j 25.+0.j]


['10' '15' 'Hello']
<U21


In [27]:
# modifying an array
arr = np.array([10, 2, 3])
print("Array before modification: ")
print(arr)
arr[0] = 1
print("Array after modification: ")
print(arr)

Array before modification: 
[10  2  3]
Array after modification: 
[1 2 3]


In [33]:
# 2D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# 3D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]) # each 2 square brackets make 1 page
print(arr)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [35]:
# To find the dimensions of an array, use ndim
arr = np.array([1, 2, 3])
print(arr.ndim)
print(arr.size)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr.size)

1
3
2
6
