In [3]:
import numpy as np

**numpy methods**

In [4]:
# To find the dimensions of an array, use ndim
print("1D Array")
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.reshape(2,3)) # (rows, cols)
print(arr.reshape(-1)) # converts 2D array to 1D array

print("\n2D Array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr.size)
print(arr.shape)

print("3D Array")
arr = np.array([[[1, 2, 3], [8, 9, 10], [4, 5, 6]]]) # (page, rows, cols)
print(arr.ndim)
print(arr.size)
print(arr.shape)

1D Array
1
6
(6,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

2D Array
2
6
(2, 3)
3D Array
3
9
(1, 3, 3)


In [5]:
a = np.arange(20, 30, 2) # 1D array
print(a)

b = list(range(21, 30, 2)) # list
print(b)

x = np.random.randint(0, 30, (3, 2)) # random number
print(x)

y = np.random.rand() # random float value bw 0 to 1
print(y)

z = np.random.randn(4) # random value, both -ve and +ve
print(z)

w = np.linspace(1, 10, 4) # equally spaced numbers over a limit
print(w)

v = np.ones((3, 2)) # creates a new array and fills it with ones OR np.ones(n)
print(v)

u = np.zeros(4) # creates a new array and fills it with zeroes
print(u)

c = np.ones(4, dtype=int) # to get integer values of ones
print(c)

mat = np.identity(3, dtype=int)
print(mat)

[20 22 24 26 28]
[21, 23, 25, 27, 29]
[[26  5]
 [12  1]
 [11 25]]
0.23253176295021794
[-0.50837509 -0.43877179  1.86764076 -0.42834353]
[ 1.  4.  7. 10.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0. 0. 0. 0.]
[1 1 1 1]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
# copy(): changes made to original will not affect copy, changes made to copy will not affect original
arr = np.array([1, 2, 3, 4, 5])
print("arr: ", arr)
copy_arr = arr.copy()
print("copy_arr: ", copy_arr)
arr[0] = 10
print("arr: ", arr)
print("copy_arr: ", copy_arr)

arr:  [1 2 3 4 5]
copy_arr:  [1 2 3 4 5]
arr:  [10  2  3  4  5]
copy_arr:  [1 2 3 4 5]


In [7]:
# view(): changes made to original will affect copy and changes made to copy will affect the original array
arr = np.array([1, 2, 3, 4, 5])
print("arr: ", arr)
view_arr = arr.view()
print("view_arr: ", view_arr)
arr[0] = 10
print("arr: ", arr)
print("view_arr: ", view_arr)

arr:  [1 2 3 4 5]
view_arr:  [1 2 3 4 5]
arr:  [10  2  3  4  5]
view_arr:  [10  2  3  4  5]


**Array Operations** <br>
i) Array to Array: Minimum 2 arrays of same length should be there <br>
ii) Array with Constant:  <br>
iii) In-built function on Array:

In [8]:
# Array to Array
# Same rows & cols
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("a: ", a)
print("b: ", b)
add = a + b
sub = a - b
mul = a * b
div = a / b
mod = a % b
print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)
print("Modulus:\n", mod)

a:  [10 20 30]
b:  [1 2 3]
Addition:
 [11 22 33]
Subtraction:
 [ 9 18 27]
Multiplication:
 [10 40 90]
Division:
 [10. 10. 10.]
Modulus:
 [0 0 0]


In [9]:
# Array to Array
# Arrays with different lengths
a = np.array([[10, 20, 30], [1, 2, 3]])
b = np.array([4, 5, 6]) # Same row is taken twice internally: BROADCASTING

print("a: ", a)
print("b: ", b)
add = a + b
sub = a - b
mul = a * b
div = a / b
mod = a % b
print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)
print("Modulus:\n", mod)

a:  [[10 20 30]
 [ 1  2  3]]
b:  [4 5 6]
Addition:
 [[14 25 36]
 [ 5  7  9]]
Subtraction:
 [[ 6 15 24]
 [-3 -3 -3]]
Multiplication:
 [[ 40 100 180]
 [  4  10  18]]
Division:
 [[2.5  4.   5.  ]
 [0.25 0.4  0.5 ]]
Modulus:
 [[2 0 0]
 [1 2 3]]


In [10]:
# Array with constant
a = np.array([10, 20, 30])

print("Adding 5: ", a+5)
print("Subtracting 1: ", a-1)
print("Multiplying by 2: ", a*2)
print("Dividing by 5: ", a/5)
print("Remainder when divided by 3: ", a%3)
print("Squaring: ", a**2)

Adding 5:  [15 25 35]
Subtracting 1:  [ 9 19 29]
Multiplying by 2:  [20 40 60]
Dividing by 5:  [2. 4. 6.]
Remainder when divided by 3:  [1 2 0]
Squaring:  [100 400 900]


In [11]:
# In-built functions on Array
a = np.array([10, 20, 30, 40, 50, 10])

print("Sum of all elements of the array is: ", np.sum(a))
print("Maximum element: ", np.max(a))
print("Minimum element: ", np.min(a))
print("Avg element: ", np.mean(a)) # avg
print("Unique elements from the array: ", np.unique(a)) # removes duplicate values
print("Square root of each element: ", np.sqrt(a)) # returns square root of each element
print("Where is element 20? ", np.where(a==10)) # returns the index of target element

b = np.array([60, 70])
print("Concatenating a and b arrays: ", np.concatenate((a, b))) # merges a and b
print("Sorted values: ", np.sort(a)) # sorts array in increasing order

Sum of all elements of the array is:  160
Maximum element:  50
Minimum element:  10
Avg element:  26.666666666666668
Unique elements from the array:  [10 20 30 40 50]
Square root of each element:  [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 3.16227766]
Where is element 20?  (array([0, 5]),)
Concatenating a and b arrays:  [10 20 30 40 50 10 60 70]
Sorted values:  [10 10 20 30 40 50]


**Indexing**: an array element can be accessed by referring to its index number.

In [15]:
# For 1D Array
a = np.array([10, 20, 30, 40])
print("For 1D Array:-")
print("1st element: ", a[0])
print("Last element: ", a[3])

# For 2D Array
b = np.array([[10, 20, 30], [40, 50, 60]])
print("\nFor 2D Array:-")
print("1st element of first row: ", b[0, 0])
print("2nd element of second row: ", b[1, 1])

# For 3D Array
c = np.array([[[10, 20, 30]], [[1, 2, 3]], [[4, 5, 6]]])
print("\nFor 3D Array:-")
print("1st element of first row of first page: ", c[0, 0, 0])
print("3rd element of first row of third page: ", c[2, 0, 2])

For 1D Array:-
1st element:  10
Last element:  40

For 2D Array:-
1st element of first row:  10
2nd element of second row:  50

For 3D Array:-
1st element of first row of first page:  10
3rd element of first row of third page:  6


**Slicing**:

In [27]:
# 1D Slicing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a[3:-1])
print(a[3:-1:2]) # a[start:end:updation_size]
print(a[3:7:1])
print(a[3::1])

[4 5 6 7 8 9]
[4 6 8]
[4 5 6 7]
[ 4  5  6  7  8  9 10]


In [41]:
# 2D Slicing
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(a[0:3,0])
print(a[0:3,1:2])
print(a[0:3,0:2]) # a[row slicing, col slicing]
print(a[2,0:2])

[10 40 70]
[[20]
 [50]
 [80]]
[[10 20]
 [40 50]
 [70 80]]
[70 80]


In [46]:
# 3D Slicing
a = np.array([[[12, 34, 56], [4, 5, 6]], [[5, 6, 7], [2, 3, 4]], [[2, 6, 4], [3, 4, 5]]])
print(a[1,0,1:]) # a[page slicing, row slicing, col slicing]
print(a[0:2,1,0:2])
print(a[0:2,1,0:])
print(a[0:2,0:2,1:])

[6 7]
[[4 5]
 [2 3]]
[[4 5 6]
 [2 3 4]]
[[[34 56]
  [ 5  6]]

 [[ 6  7]
  [ 3  4]]]
